# Generated by Django 4.2.26 on 2025-11-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('job_role', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('slack_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('slack_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slack_workspace_id', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'permissions': [('manage_employees', 'Can manage employees'), ('view_all_clients', 'Can view all clients'), ('manage_all_clients', 'Can manage all clients'), ('view_payments', 'Can view payments'), ('manage_payments', 'Can manage payments')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('ceo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('niche', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('trz_api_key', models.TextField(blank=True, null=True)),
                ('domain_name_main', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trz_group_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('trz_admin_user_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('ghl_location_id', models.TextField(blank=True, null=True, unique=True)),
                ('short_url_domain', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('onboarding', 'Onboarding'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('coaching_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trz_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_start_date', models.DateField(blank=True, null=True)),
                ('client_end_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_origin', models.TextField(blank=True, null=True)),
                ('notice_given', models.BooleanField(default=False)),
                ('no_more_payments', models.BooleanField(default=False)),
                ('timezone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pif_months', models.IntegerField(blank=True, null=True)),
                ('stripe_account', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_schedule', models.CharField(blank=True, choices=[('PIF', 'PIF'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('package_end_date', models.DateField(blank=True, null=True)),
                ('package_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payments_left', models.IntegerField(blank=True, null=True)),
                ('review_type', models.CharField(blank=True, max_length=255, null=True)),
                ('checkin_type', models.CharField(blank=True, max_length=255, null=True)),
                ('checkin_day', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_term', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'client_packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_account', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('failed', 'Failed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('instalment_number', models.IntegerField(blank=True, null=True)),
                ('schedule_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instalments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('native_account_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('incomplete', 'Incomplete')], max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('stripe_account', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'stripe_customers',
                'managed': False,
            },
        ),
    ]
