// Country codes with flags and dial codes
// Flag emojis are generated using country ISO codes

export interface Country {
  name: string;
  code: string; // ISO country code
  dialCode: string;
  flag: string; // Flag emoji
  priority?: boolean; // For popular countries
}

// Helper function to get flag emoji from country code
const getFlag = (countryCode: string): string => {
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
};

export const COUNTRY_CODES: Country[] = [
  // Popular countries (shown first)
  { name: "United States", code: "US", dialCode: "+1", flag: getFlag("US"), priority: true },
  { name: "United Kingdom", code: "GB", dialCode: "+44", flag: getFlag("GB"), priority: true },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971", flag: getFlag("AE"), priority: true },
  { name: "Morocco", code: "MA", dialCode: "+212", flag: getFlag("MA"), priority: true },
  { name: "Canada", code: "CA", dialCode: "+1", flag: getFlag("CA"), priority: true },
  
  // All other countries (alphabetical)
  { name: "Afghanistan", code: "AF", dialCode: "+93", flag: getFlag("AF") },
  { name: "Albania", code: "AL", dialCode: "+355", flag: getFlag("AL") },
  { name: "Algeria", code: "DZ", dialCode: "+213", flag: getFlag("DZ") },
  { name: "Andorra", code: "AD", dialCode: "+376", flag: getFlag("AD") },
  { name: "Angola", code: "AO", dialCode: "+244", flag: getFlag("AO") },
  { name: "Argentina", code: "AR", dialCode: "+54", flag: getFlag("AR") },
  { name: "Armenia", code: "AM", dialCode: "+374", flag: getFlag("AM") },
  { name: "Aruba", code: "AW", dialCode: "+297", flag: getFlag("AW") },
  { name: "Australia", code: "AU", dialCode: "+61", flag: getFlag("AU") },
  { name: "Austria", code: "AT", dialCode: "+43", flag: getFlag("AT") },
  { name: "Azerbaijan", code: "AZ", dialCode: "+994", flag: getFlag("AZ") },
  { name: "Bahrain", code: "BH", dialCode: "+973", flag: getFlag("BH") },
  { name: "Bangladesh", code: "BD", dialCode: "+880", flag: getFlag("BD") },
  { name: "Belarus", code: "BY", dialCode: "+375", flag: getFlag("BY") },
  { name: "Belgium", code: "BE", dialCode: "+32", flag: getFlag("BE") },
  { name: "Belize", code: "BZ", dialCode: "+501", flag: getFlag("BZ") },
  { name: "Benin", code: "BJ", dialCode: "+229", flag: getFlag("BJ") },
  { name: "Bhutan", code: "BT", dialCode: "+975", flag: getFlag("BT") },
  { name: "Bolivia", code: "BO", dialCode: "+591", flag: getFlag("BO") },
  { name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387", flag: getFlag("BA") },
  { name: "Botswana", code: "BW", dialCode: "+267", flag: getFlag("BW") },
  { name: "Brazil", code: "BR", dialCode: "+55", flag: getFlag("BR") },
  { name: "British Indian Ocean Territory", code: "IO", dialCode: "+246", flag: getFlag("IO") },
  { name: "Brunei", code: "BN", dialCode: "+673", flag: getFlag("BN") },
  { name: "Bulgaria", code: "BG", dialCode: "+359", flag: getFlag("BG") },
  { name: "Burkina Faso", code: "BF", dialCode: "+226", flag: getFlag("BF") },
  { name: "Burundi", code: "BI", dialCode: "+257", flag: getFlag("BI") },
  { name: "Cambodia", code: "KH", dialCode: "+855", flag: getFlag("KH") },
  { name: "Cameroon", code: "CM", dialCode: "+237", flag: getFlag("CM") },
  { name: "Cape Verde", code: "CV", dialCode: "+238", flag: getFlag("CV") },
  { name: "Central African Republic", code: "CF", dialCode: "+236", flag: getFlag("CF") },
  { name: "Chad", code: "TD", dialCode: "+235", flag: getFlag("TD") },
  { name: "Chile", code: "CL", dialCode: "+56", flag: getFlag("CL") },
  { name: "China", code: "CN", dialCode: "+86", flag: getFlag("CN") },
  { name: "Colombia", code: "CO", dialCode: "+57", flag: getFlag("CO") },
  { name: "Comoros", code: "KM", dialCode: "+269", flag: getFlag("KM") },
  { name: "Cook Islands", code: "CK", dialCode: "+682", flag: getFlag("CK") },
  { name: "Costa Rica", code: "CR", dialCode: "+506", flag: getFlag("CR") },
  { name: "Croatia", code: "HR", dialCode: "+385", flag: getFlag("HR") },
  { name: "Cuba", code: "CU", dialCode: "+53", flag: getFlag("CU") },
  { name: "Curaçao", code: "CW", dialCode: "+599", flag: getFlag("CW") },
  { name: "Cyprus", code: "CY", dialCode: "+357", flag: getFlag("CY") },
  { name: "Czech Republic", code: "CZ", dialCode: "+420", flag: getFlag("CZ") },
  { name: "Democratic Republic of the Congo", code: "CD", dialCode: "+243", flag: getFlag("CD") },
  { name: "Denmark", code: "DK", dialCode: "+45", flag: getFlag("DK") },
  { name: "Djibouti", code: "DJ", dialCode: "+253", flag: getFlag("DJ") },
  { name: "East Timor", code: "TL", dialCode: "+670", flag: getFlag("TL") },
  { name: "Ecuador", code: "EC", dialCode: "+593", flag: getFlag("EC") },
  { name: "Egypt", code: "EG", dialCode: "+20", flag: getFlag("EG") },
  { name: "El Salvador", code: "SV", dialCode: "+503", flag: getFlag("SV") },
  { name: "Equatorial Guinea", code: "GQ", dialCode: "+240", flag: getFlag("GQ") },
  { name: "Eritrea", code: "ER", dialCode: "+291", flag: getFlag("ER") },
  { name: "Estonia", code: "EE", dialCode: "+372", flag: getFlag("EE") },
  { name: "Eswatini", code: "SZ", dialCode: "+268", flag: getFlag("SZ") },
  { name: "Ethiopia", code: "ET", dialCode: "+251", flag: getFlag("ET") },
  { name: "Falkland Islands", code: "FK", dialCode: "+500", flag: getFlag("FK") },
  { name: "Faroe Islands", code: "FO", dialCode: "+298", flag: getFlag("FO") },
  { name: "Fiji", code: "FJ", dialCode: "+679", flag: getFlag("FJ") },
  { name: "Finland", code: "FI", dialCode: "+358", flag: getFlag("FI") },
  { name: "France", code: "FR", dialCode: "+33", flag: getFlag("FR") },
  { name: "French Guiana", code: "GF", dialCode: "+594", flag: getFlag("GF") },
  { name: "French Polynesia", code: "PF", dialCode: "+689", flag: getFlag("PF") },
  { name: "Gabon", code: "GA", dialCode: "+241", flag: getFlag("GA") },
  { name: "Gambia", code: "GM", dialCode: "+220", flag: getFlag("GM") },
  { name: "Georgia", code: "GE", dialCode: "+995", flag: getFlag("GE") },
  { name: "Germany", code: "DE", dialCode: "+49", flag: getFlag("DE") },
  { name: "Ghana", code: "GH", dialCode: "+233", flag: getFlag("GH") },
  { name: "Gibraltar", code: "GI", dialCode: "+350", flag: getFlag("GI") },
  { name: "Greece", code: "GR", dialCode: "+30", flag: getFlag("GR") },
  { name: "Greenland", code: "GL", dialCode: "+299", flag: getFlag("GL") },
  { name: "Guadeloupe", code: "GP", dialCode: "+590", flag: getFlag("GP") },
  { name: "Guatemala", code: "GT", dialCode: "+502", flag: getFlag("GT") },
  { name: "Guinea", code: "GN", dialCode: "+224", flag: getFlag("GN") },
  { name: "Guinea-Bissau", code: "GW", dialCode: "+245", flag: getFlag("GW") },
  { name: "Guyana", code: "GY", dialCode: "+592", flag: getFlag("GY") },
  { name: "Haiti", code: "HT", dialCode: "+509", flag: getFlag("HT") },
  { name: "Honduras", code: "HN", dialCode: "+504", flag: getFlag("HN") },
  { name: "Hong Kong", code: "HK", dialCode: "+852", flag: getFlag("HK") },
  { name: "Hungary", code: "HU", dialCode: "+36", flag: getFlag("HU") },
  { name: "Iceland", code: "IS", dialCode: "+354", flag: getFlag("IS") },
  { name: "India", code: "IN", dialCode: "+91", flag: getFlag("IN") },
  { name: "Indonesia", code: "ID", dialCode: "+62", flag: getFlag("ID") },
  { name: "Iran", code: "IR", dialCode: "+98", flag: getFlag("IR") },
  { name: "Iraq", code: "IQ", dialCode: "+964", flag: getFlag("IQ") },
  { name: "Ireland", code: "IE", dialCode: "+353", flag: getFlag("IE") },
  { name: "Israel", code: "IL", dialCode: "+972", flag: getFlag("IL") },
  { name: "Italy", code: "IT", dialCode: "+39", flag: getFlag("IT") },
  { name: "Ivory Coast", code: "CI", dialCode: "+225", flag: getFlag("CI") },
  { name: "Japan", code: "JP", dialCode: "+81", flag: getFlag("JP") },
  { name: "Jordan", code: "JO", dialCode: "+962", flag: getFlag("JO") },
  { name: "Kenya", code: "KE", dialCode: "+254", flag: getFlag("KE") },
  { name: "Kiribati", code: "KI", dialCode: "+686", flag: getFlag("KI") },
  { name: "Kosovo", code: "XK", dialCode: "+383", flag: getFlag("XK") },
  { name: "Kuwait", code: "KW", dialCode: "+965", flag: getFlag("KW") },
  { name: "Kyrgyzstan", code: "KG", dialCode: "+996", flag: getFlag("KG") },
  { name: "Laos", code: "LA", dialCode: "+856", flag: getFlag("LA") },
  { name: "Latvia", code: "LV", dialCode: "+371", flag: getFlag("LV") },
  { name: "Lebanon", code: "LB", dialCode: "+961", flag: getFlag("LB") },
  { name: "Lesotho", code: "LS", dialCode: "+266", flag: getFlag("LS") },
  { name: "Liberia", code: "LR", dialCode: "+231", flag: getFlag("LR") },
  { name: "Libya", code: "LY", dialCode: "+218", flag: getFlag("LY") },
  { name: "Liechtenstein", code: "LI", dialCode: "+423", flag: getFlag("LI") },
  { name: "Lithuania", code: "LT", dialCode: "+370", flag: getFlag("LT") },
  { name: "Luxembourg", code: "LU", dialCode: "+352", flag: getFlag("LU") },
  { name: "Macau", code: "MO", dialCode: "+853", flag: getFlag("MO") },
  { name: "Madagascar", code: "MG", dialCode: "+261", flag: getFlag("MG") },
  { name: "Malawi", code: "MW", dialCode: "+265", flag: getFlag("MW") },
  { name: "Malaysia", code: "MY", dialCode: "+60", flag: getFlag("MY") },
  { name: "Maldives", code: "MV", dialCode: "+960", flag: getFlag("MV") },
  { name: "Mali", code: "ML", dialCode: "+223", flag: getFlag("ML") },
  { name: "Malta", code: "MT", dialCode: "+356", flag: getFlag("MT") },
  { name: "Marshall Islands", code: "MH", dialCode: "+692", flag: getFlag("MH") },
  { name: "Martinique", code: "MQ", dialCode: "+596", flag: getFlag("MQ") },
  { name: "Mauritania", code: "MR", dialCode: "+222", flag: getFlag("MR") },
  { name: "Mauritius", code: "MU", dialCode: "+230", flag: getFlag("MU") },
  { name: "Mexico", code: "MX", dialCode: "+52", flag: getFlag("MX") },
  { name: "Micronesia", code: "FM", dialCode: "+691", flag: getFlag("FM") },
  { name: "Moldova", code: "MD", dialCode: "+373", flag: getFlag("MD") },
  { name: "Monaco", code: "MC", dialCode: "+377", flag: getFlag("MC") },
  { name: "Mongolia", code: "MN", dialCode: "+976", flag: getFlag("MN") },
  { name: "Montenegro", code: "ME", dialCode: "+382", flag: getFlag("ME") },
  { name: "Mozambique", code: "MZ", dialCode: "+258", flag: getFlag("MZ") },
  { name: "Myanmar", code: "MM", dialCode: "+95", flag: getFlag("MM") },
  { name: "Namibia", code: "NA", dialCode: "+264", flag: getFlag("NA") },
  { name: "Nauru", code: "NR", dialCode: "+674", flag: getFlag("NR") },
  { name: "Nepal", code: "NP", dialCode: "+977", flag: getFlag("NP") },
  { name: "Netherlands", code: "NL", dialCode: "+31", flag: getFlag("NL") },
  { name: "New Caledonia", code: "NC", dialCode: "+687", flag: getFlag("NC") },
  { name: "New Zealand", code: "NZ", dialCode: "+64", flag: getFlag("NZ") },
  { name: "Nicaragua", code: "NI", dialCode: "+505", flag: getFlag("NI") },
  { name: "Niger", code: "NE", dialCode: "+227", flag: getFlag("NE") },
  { name: "Nigeria", code: "NG", dialCode: "+234", flag: getFlag("NG") },
  { name: "Niue", code: "NU", dialCode: "+683", flag: getFlag("NU") },
  { name: "Norfolk Island", code: "NF", dialCode: "+672", flag: getFlag("NF") },
  { name: "North Korea", code: "KP", dialCode: "+850", flag: getFlag("KP") },
  { name: "North Macedonia", code: "MK", dialCode: "+389", flag: getFlag("MK") },
  { name: "Norway", code: "NO", dialCode: "+47", flag: getFlag("NO") },
  { name: "Oman", code: "OM", dialCode: "+968", flag: getFlag("OM") },
  { name: "Pakistan", code: "PK", dialCode: "+92", flag: getFlag("PK") },
  { name: "Palau", code: "PW", dialCode: "+680", flag: getFlag("PW") },
  { name: "Palestine", code: "PS", dialCode: "+970", flag: getFlag("PS") },
  { name: "Panama", code: "PA", dialCode: "+507", flag: getFlag("PA") },
  { name: "Papua New Guinea", code: "PG", dialCode: "+675", flag: getFlag("PG") },
  { name: "Paraguay", code: "PY", dialCode: "+595", flag: getFlag("PY") },
  { name: "Peru", code: "PE", dialCode: "+51", flag: getFlag("PE") },
  { name: "Philippines", code: "PH", dialCode: "+63", flag: getFlag("PH") },
  { name: "Poland", code: "PL", dialCode: "+48", flag: getFlag("PL") },
  { name: "Portugal", code: "PT", dialCode: "+351", flag: getFlag("PT") },
  { name: "Qatar", code: "QA", dialCode: "+974", flag: getFlag("QA") },
  { name: "Republic of the Congo", code: "CG", dialCode: "+242", flag: getFlag("CG") },
  { name: "Réunion", code: "RE", dialCode: "+262", flag: getFlag("RE") },
  { name: "Romania", code: "RO", dialCode: "+40", flag: getFlag("RO") },
  { name: "Russia", code: "RU", dialCode: "+7", flag: getFlag("RU") },
  { name: "Rwanda", code: "RW", dialCode: "+250", flag: getFlag("RW") },
  { name: "Saint Helena", code: "SH", dialCode: "+290", flag: getFlag("SH") },
  { name: "Saint Pierre and Miquelon", code: "PM", dialCode: "+508", flag: getFlag("PM") },
  { name: "Samoa", code: "WS", dialCode: "+685", flag: getFlag("WS") },
  { name: "San Marino", code: "SM", dialCode: "+378", flag: getFlag("SM") },
  { name: "São Tomé and Príncipe", code: "ST", dialCode: "+239", flag: getFlag("ST") },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966", flag: getFlag("SA") },
  { name: "Senegal", code: "SN", dialCode: "+221", flag: getFlag("SN") },
  { name: "Serbia", code: "RS", dialCode: "+381", flag: getFlag("RS") },
  { name: "Seychelles", code: "SC", dialCode: "+248", flag: getFlag("SC") },
  { name: "Sierra Leone", code: "SL", dialCode: "+232", flag: getFlag("SL") },
  { name: "Singapore", code: "SG", dialCode: "+65", flag: getFlag("SG") },
  { name: "Slovakia", code: "SK", dialCode: "+421", flag: getFlag("SK") },
  { name: "Slovenia", code: "SI", dialCode: "+386", flag: getFlag("SI") },
  { name: "Solomon Islands", code: "SB", dialCode: "+677", flag: getFlag("SB") },
  { name: "Somalia", code: "SO", dialCode: "+252", flag: getFlag("SO") },
  { name: "South Africa", code: "ZA", dialCode: "+27", flag: getFlag("ZA") },
  { name: "South Korea", code: "KR", dialCode: "+82", flag: getFlag("KR") },
  { name: "Spain", code: "ES", dialCode: "+34", flag: getFlag("ES") },
  { name: "Sri Lanka", code: "LK", dialCode: "+94", flag: getFlag("LK") },
  { name: "Sudan", code: "SD", dialCode: "+249", flag: getFlag("SD") },
  { name: "Suriname", code: "SR", dialCode: "+597", flag: getFlag("SR") },
  { name: "Sweden", code: "SE", dialCode: "+46", flag: getFlag("SE") },
  { name: "Switzerland", code: "CH", dialCode: "+41", flag: getFlag("CH") },
  { name: "Syria", code: "SY", dialCode: "+963", flag: getFlag("SY") },
  { name: "Taiwan", code: "TW", dialCode: "+886", flag: getFlag("TW") },
  { name: "Tajikistan", code: "TJ", dialCode: "+992", flag: getFlag("TJ") },
  { name: "Tanzania", code: "TZ", dialCode: "+255", flag: getFlag("TZ") },
  { name: "Thailand", code: "TH", dialCode: "+66", flag: getFlag("TH") },
  { name: "Togo", code: "TG", dialCode: "+228", flag: getFlag("TG") },
  { name: "Tokelau", code: "TK", dialCode: "+690", flag: getFlag("TK") },
  { name: "Tonga", code: "TO", dialCode: "+676", flag: getFlag("TO") },
  { name: "Tunisia", code: "TN", dialCode: "+216", flag: getFlag("TN") },
  { name: "Turkey", code: "TR", dialCode: "+90", flag: getFlag("TR") },
  { name: "Turkmenistan", code: "TM", dialCode: "+993", flag: getFlag("TM") },
  { name: "Tuvalu", code: "TV", dialCode: "+688", flag: getFlag("TV") },
  { name: "Uganda", code: "UG", dialCode: "+256", flag: getFlag("UG") },
  { name: "Ukraine", code: "UA", dialCode: "+380", flag: getFlag("UA") },
  { name: "Uruguay", code: "UY", dialCode: "+598", flag: getFlag("UY") },
  { name: "Uzbekistan", code: "UZ", dialCode: "+998", flag: getFlag("UZ") },
  { name: "Vanuatu", code: "VU", dialCode: "+678", flag: getFlag("VU") },
  { name: "Venezuela", code: "VE", dialCode: "+58", flag: getFlag("VE") },
  { name: "Vietnam", code: "VN", dialCode: "+84", flag: getFlag("VN") },
  { name: "Wallis and Futuna", code: "WF", dialCode: "+681", flag: getFlag("WF") },
  { name: "Yemen", code: "YE", dialCode: "+967", flag: getFlag("YE") },
  { name: "Zambia", code: "ZM", dialCode: "+260", flag: getFlag("ZM") },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263", flag: getFlag("ZW") },
];

// Get popular countries
export const getPopularCountries = (): Country[] => {
  return COUNTRY_CODES.filter(country => country.priority);
};

// Get all countries sorted alphabetically
export const getAllCountries = (): Country[] => {
  return COUNTRY_CODES.filter(country => !country.priority).sort((a, b) => 
    a.name.localeCompare(b.name)
  );
};
