-- Add reviews form support with interval scheduling
-- This migration adds:
-- 1. Interval fields to check_in_schedules for reviews scheduling
-- 2. Reviews link fields to clients table

-- =============================================================================
-- Step 1: Add interval fields to check_in_schedules
-- =============================================================================

-- interval_type: 'weekly' or 'monthly'
ALTER TABLE check_in_schedules ADD COLUMN IF NOT EXISTS interval_type VARCHAR(10);

-- interval_count: number between 1-12 (every N weeks or N months)
ALTER TABLE check_in_schedules ADD COLUMN IF NOT EXISTS interval_count INTEGER;

-- last_triggered_at: tracks last execution for weekly interval calculations
ALTER TABLE check_in_schedules ADD COLUMN IF NOT EXISTS last_triggered_at TIMESTAMP;

-- Add check constraint for interval_type values
ALTER TABLE check_in_schedules ADD CONSTRAINT check_in_schedules_interval_type_check 
    CHECK (interval_type IS NULL OR interval_type IN ('weekly', 'monthly'));

-- Add check constraint for interval_count range (1-12)
ALTER TABLE check_in_schedules ADD CONSTRAINT check_in_schedules_interval_count_check 
    CHECK (interval_count IS NULL OR (interval_count >= 1 AND interval_count <= 12));

-- =============================================================================
-- Step 2: Add reviews link fields to clients
-- =============================================================================

-- reviews_link: UUID for accessing reviews form
ALTER TABLE clients ADD COLUMN IF NOT EXISTS reviews_link UUID DEFAULT gen_random_uuid() UNIQUE;

-- short_reviews_link: shortened URL from URL shortener service
ALTER TABLE clients ADD COLUMN IF NOT EXISTS short_reviews_link TEXT;

-- Create index for faster lookups by reviews_link
CREATE INDEX IF NOT EXISTS idx_clients_reviews_link ON clients(reviews_link);

-- Populate reviews_link for existing clients that don't have one
UPDATE clients SET reviews_link = gen_random_uuid() WHERE reviews_link IS NULL;

-- =============================================================================
-- Step 3: Add comments
-- =============================================================================

COMMENT ON COLUMN check_in_schedules.interval_type IS 'Interval type for reviews: weekly or monthly';
COMMENT ON COLUMN check_in_schedules.interval_count IS 'Number of weeks/months between reviews (1-12)';
COMMENT ON COLUMN check_in_schedules.last_triggered_at IS 'Last time the schedule was triggered (for weekly interval tracking)';
COMMENT ON COLUMN clients.reviews_link IS 'Permanent UUID link for reviews form access';
COMMENT ON COLUMN clients.short_reviews_link IS 'Shortened URL for reviews form (generated by URL shortener)';

