revoke delete on table "public"."stripe_api_keys" from "anon";

revoke insert on table "public"."stripe_api_keys" from "anon";

revoke references on table "public"."stripe_api_keys" from "anon";

revoke select on table "public"."stripe_api_keys" from "anon";

revoke trigger on table "public"."stripe_api_keys" from "anon";

revoke truncate on table "public"."stripe_api_keys" from "anon";

revoke update on table "public"."stripe_api_keys" from "anon";

revoke delete on table "public"."stripe_api_keys" from "authenticated";

revoke insert on table "public"."stripe_api_keys" from "authenticated";

revoke references on table "public"."stripe_api_keys" from "authenticated";

revoke select on table "public"."stripe_api_keys" from "authenticated";

revoke trigger on table "public"."stripe_api_keys" from "authenticated";

revoke truncate on table "public"."stripe_api_keys" from "authenticated";

revoke update on table "public"."stripe_api_keys" from "authenticated";

revoke delete on table "public"."stripe_api_keys" from "service_role";

revoke insert on table "public"."stripe_api_keys" from "service_role";

revoke references on table "public"."stripe_api_keys" from "service_role";

revoke select on table "public"."stripe_api_keys" from "service_role";

revoke trigger on table "public"."stripe_api_keys" from "service_role";

revoke truncate on table "public"."stripe_api_keys" from "service_role";

revoke update on table "public"."stripe_api_keys" from "service_role";

alter table "public"."stripe_api_keys" drop constraint "stripe_api_keys_api_key_key";

alter table "public"."stripe_api_keys" drop constraint "stripe_api_keys_client_account_id_fkey";

-- Drop FK constraint BEFORE dropping the unique constraint it depends on
alter table "public"."stripe_customers" drop constraint "stripe_customers_stripe_account_fkey";

alter table "public"."stripe_api_keys" drop constraint "stripe_api_keys_stripe_account_key";

alter table "public"."stripe_api_keys" drop constraint "stripe_api_keys_pkey";

drop index if exists "public"."stripe_api_keys_api_key_key";

drop index if exists "public"."stripe_api_keys_pkey";

drop index if exists "public"."stripe_api_keys_stripe_account_key";

drop table "public"."stripe_api_keys";


  create table "public"."stripe_accounts" (
    "created_at" timestamp with time zone not null default now(),
    "stripe_account" character varying,
    "updated_at" timestamp with time zone not null default now(),
    "api_key" character varying,
    "client_account_id" integer,
    "id" integer generated by default as identity not null,
    "is_active" boolean not null,
    "checkout_thanks_url" text,
    "checkout_cancelled_url" text,
    "is_primary" boolean,
    "stripe_client_id" character varying(255),
    "default_currency" text
      );


alter table "public"."stripe_accounts" enable row level security;

alter table "public"."accounts" add column "company_currency" text;

alter table "public"."check_in_forms" enable row level security;

alter table "public"."check_in_schedules" enable row level security;

alter table "public"."check_in_submissions" enable row level security;

alter table "public"."clients" add column "created_at" timestamp with time zone not null default now();

alter table "public"."clients" add column "updated_at" timestamp with time zone;

alter table "public"."employee_role_assignments" enable row level security;

alter table "public"."employees" add column "first_name" text;

alter table "public"."employees" add column "last_name" text;

alter table "public"."payments" drop column "currency";

alter table "public"."payments" add column "company_currency_amount" numeric;

alter table "public"."payments" add column "paid_currency" text;

CREATE UNIQUE INDEX stripe_api_keys_api_key_key ON public.stripe_accounts USING btree (api_key);

CREATE UNIQUE INDEX stripe_api_keys_pkey ON public.stripe_accounts USING btree (id);

CREATE UNIQUE INDEX stripe_api_keys_stripe_account_key ON public.stripe_accounts USING btree (stripe_account);

alter table "public"."stripe_accounts" add constraint "stripe_api_keys_pkey" PRIMARY KEY using index "stripe_api_keys_pkey";

alter table "public"."stripe_accounts" add constraint "stripe_api_keys_api_key_key" UNIQUE using index "stripe_api_keys_api_key_key";

alter table "public"."stripe_accounts" add constraint "stripe_api_keys_client_account_id_fkey" FOREIGN KEY (client_account_id) REFERENCES public.accounts(id) ON UPDATE CASCADE not valid;

alter table "public"."stripe_accounts" validate constraint "stripe_api_keys_client_account_id_fkey";

alter table "public"."stripe_accounts" add constraint "stripe_api_keys_stripe_account_key" UNIQUE using index "stripe_api_keys_stripe_account_key";

alter table "public"."stripe_customers" add constraint "stripe_customers_stripe_account_fkey" FOREIGN KEY (stripe_account) REFERENCES public.stripe_accounts(stripe_account) ON UPDATE CASCADE not valid;

alter table "public"."stripe_customers" validate constraint "stripe_customers_stripe_account_fkey";

grant delete on table "public"."stripe_accounts" to "anon";

grant insert on table "public"."stripe_accounts" to "anon";

grant references on table "public"."stripe_accounts" to "anon";

grant select on table "public"."stripe_accounts" to "anon";

grant trigger on table "public"."stripe_accounts" to "anon";

grant truncate on table "public"."stripe_accounts" to "anon";

grant update on table "public"."stripe_accounts" to "anon";

grant delete on table "public"."stripe_accounts" to "authenticated";

grant insert on table "public"."stripe_accounts" to "authenticated";

grant references on table "public"."stripe_accounts" to "authenticated";

grant select on table "public"."stripe_accounts" to "authenticated";

grant trigger on table "public"."stripe_accounts" to "authenticated";

grant truncate on table "public"."stripe_accounts" to "authenticated";

grant update on table "public"."stripe_accounts" to "authenticated";

grant delete on table "public"."stripe_accounts" to "service_role";

grant insert on table "public"."stripe_accounts" to "service_role";

grant references on table "public"."stripe_accounts" to "service_role";

grant select on table "public"."stripe_accounts" to "service_role";

grant trigger on table "public"."stripe_accounts" to "service_role";

grant truncate on table "public"."stripe_accounts" to "service_role";

grant update on table "public"."stripe_accounts" to "service_role";


