


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."client_package_status" AS ENUM (
    'active',
    'inactive'
);


ALTER TYPE "public"."client_package_status" OWNER TO "postgres";


CREATE TYPE "public"."client_status" AS ENUM (
    'active',
    'inactive',
    'onboarding',
    'paused',
    'cancelled'
);


ALTER TYPE "public"."client_status" OWNER TO "postgres";


CREATE TYPE "public"."employee_status" AS ENUM (
    'active',
    'inactive'
);


ALTER TYPE "public"."employee_status" OWNER TO "postgres";


CREATE TYPE "public"."instalment_status" AS ENUM (
    'open',
    'paid',
    'failed',
    'closed'
);


ALTER TYPE "public"."instalment_status" OWNER TO "postgres";


CREATE TYPE "public"."payment_schedule" AS ENUM (
    'PIF',
    'Monthly',
    'Quarterly',
    'Yearly'
);


ALTER TYPE "public"."payment_schedule" OWNER TO "postgres";


CREATE TYPE "public"."payment_status" AS ENUM (
    'paid',
    'failed',
    'refunded',
    'disputed',
    'incomplete'
);


ALTER TYPE "public"."payment_status" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."accounts" (
    "id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "email" character varying(255),
    "ceo_name" character varying(255),
    "niche" character varying(255),
    "location" "text",
    "stripe_api_key" "text",
    "trz_api_key" "text",
    "domain_name_main" character varying(255),
    "website_url" character varying(255),
    "date_joined" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "trz_group_id" integer,
    "trz_admin_user_id" integer,
    "ghl_location_id" "text",
    "short_url_domain" "text",
    "timezone" "text"
);


ALTER TABLE "public"."accounts" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."accounts_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."accounts_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."accounts_id_seq" OWNED BY "public"."accounts"."id";



CREATE TABLE IF NOT EXISTS "public"."auth_group" (
    "id" integer NOT NULL,
    "name" character varying(150) NOT NULL
);


ALTER TABLE "public"."auth_group" OWNER TO "postgres";


ALTER TABLE "public"."auth_group" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_group_permissions" (
    "id" bigint NOT NULL,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_group_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_group_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_permission" (
    "id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL
);


ALTER TABLE "public"."auth_permission" OWNER TO "postgres";


ALTER TABLE "public"."auth_permission" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_permission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_user" (
    "id" integer NOT NULL,
    "password" character varying(128) NOT NULL,
    "last_login" timestamp with time zone,
    "is_superuser" boolean NOT NULL,
    "username" character varying(150) NOT NULL,
    "first_name" character varying(150) NOT NULL,
    "last_name" character varying(150) NOT NULL,
    "email" character varying(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."auth_user" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."auth_user_groups" (
    "id" bigint NOT NULL,
    "user_id" integer NOT NULL,
    "group_id" integer NOT NULL
);


ALTER TABLE "public"."auth_user_groups" OWNER TO "postgres";


ALTER TABLE "public"."auth_user_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."auth_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_user_user_permissions" (
    "id" bigint NOT NULL,
    "user_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_user_user_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_user_user_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."authtoken_token" (
    "key" character varying(40) NOT NULL,
    "created" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL
);


ALTER TABLE "public"."authtoken_token" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."click_analytics" (
    "id" bigint NOT NULL,
    "clicked_at" timestamp with time zone NOT NULL,
    "ip_address" "inet",
    "user_agent" "text" NOT NULL,
    "referer" character varying(2048) NOT NULL,
    "country" character varying(2) NOT NULL,
    "city" character varying(100) NOT NULL,
    "short_url_id" bigint NOT NULL
);


ALTER TABLE "public"."click_analytics" OWNER TO "postgres";


ALTER TABLE "public"."click_analytics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."click_analytics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."client_packages" (
    "id" integer NOT NULL,
    "client_id" integer NOT NULL,
    "package_id" integer NOT NULL,
    "custom_price" numeric(10,2),
    "monthly_payment_amount" numeric(10,2),
    "pif_months" integer,
    "stripe_account" character varying(255),
    "payment_schedule" "public"."payment_schedule",
    "start_date" "date",
    "package_end_date" "date",
    "package_type" character varying(255),
    "payments_left" integer,
    "review_type" character varying(255),
    "checkin_type" character varying(255),
    "checkin_day" character varying(50),
    "minimum_term" integer,
    "status" "public"."client_package_status" DEFAULT 'active'::"public"."client_package_status"
);


ALTER TABLE "public"."client_packages" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."client_packages_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."client_packages_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."client_packages_id_seq" OWNED BY "public"."client_packages"."id";



CREATE TABLE IF NOT EXISTS "public"."clients" (
    "id" integer NOT NULL,
    "account_id" integer NOT NULL,
    "first_name" character varying(255) NOT NULL,
    "last_name" character varying(255),
    "email" character varying(255) NOT NULL,
    "status" "public"."client_status" DEFAULT 'active'::"public"."client_status",
    "address" "text",
    "instagram_handle" character varying(255),
    "ghl_id" character varying(255),
    "coaching_app_id" character varying(255),
    "trz_id" character varying(255),
    "client_start_date" "date",
    "client_end_date" "date",
    "dob" "date",
    "country" character varying(100),
    "state" character varying(100),
    "currency" character varying(10),
    "gender" character varying(50),
    "lead_origin" "text",
    "notice_given" boolean DEFAULT false,
    "no_more_payments" boolean DEFAULT false,
    "coach_id" integer,
    "closer_id" integer,
    "setter_id" integer,
    "timezone" "text"
);


ALTER TABLE "public"."clients" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."clients_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."clients_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."clients_id_seq" OWNED BY "public"."clients"."id";



CREATE TABLE IF NOT EXISTS "public"."django_admin_log" (
    "id" integer NOT NULL,
    "action_time" timestamp with time zone NOT NULL,
    "object_id" "text",
    "object_repr" character varying(200) NOT NULL,
    "action_flag" smallint NOT NULL,
    "change_message" "text" NOT NULL,
    "content_type_id" integer,
    "user_id" integer NOT NULL,
    CONSTRAINT "django_admin_log_action_flag_check" CHECK (("action_flag" >= 0))
);


ALTER TABLE "public"."django_admin_log" OWNER TO "postgres";


ALTER TABLE "public"."django_admin_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_admin_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_celery_beat_clockedschedule" (
    "id" integer NOT NULL,
    "clocked_time" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_celery_beat_clockedschedule" OWNER TO "postgres";


ALTER TABLE "public"."django_celery_beat_clockedschedule" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_celery_beat_clockedschedule_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_celery_beat_crontabschedule" (
    "id" integer NOT NULL,
    "minute" character varying(240) NOT NULL,
    "hour" character varying(96) NOT NULL,
    "day_of_week" character varying(64) NOT NULL,
    "day_of_month" character varying(124) NOT NULL,
    "month_of_year" character varying(64) NOT NULL,
    "timezone" character varying(63) NOT NULL
);


ALTER TABLE "public"."django_celery_beat_crontabschedule" OWNER TO "postgres";


ALTER TABLE "public"."django_celery_beat_crontabschedule" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_celery_beat_crontabschedule_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_celery_beat_intervalschedule" (
    "id" integer NOT NULL,
    "every" integer NOT NULL,
    "period" character varying(24) NOT NULL
);


ALTER TABLE "public"."django_celery_beat_intervalschedule" OWNER TO "postgres";


ALTER TABLE "public"."django_celery_beat_intervalschedule" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_celery_beat_intervalschedule_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_celery_beat_periodictask" (
    "id" integer NOT NULL,
    "name" character varying(200) NOT NULL,
    "task" character varying(200) NOT NULL,
    "args" "text" NOT NULL,
    "kwargs" "text" NOT NULL,
    "queue" character varying(200),
    "exchange" character varying(200),
    "routing_key" character varying(200),
    "expires" timestamp with time zone,
    "enabled" boolean NOT NULL,
    "last_run_at" timestamp with time zone,
    "total_run_count" integer NOT NULL,
    "date_changed" timestamp with time zone NOT NULL,
    "description" "text" NOT NULL,
    "crontab_id" integer,
    "interval_id" integer,
    "solar_id" integer,
    "one_off" boolean NOT NULL,
    "start_time" timestamp with time zone,
    "priority" integer,
    "headers" "text" NOT NULL,
    "clocked_id" integer,
    "expire_seconds" integer,
    CONSTRAINT "django_celery_beat_periodictask_expire_seconds_check" CHECK (("expire_seconds" >= 0)),
    CONSTRAINT "django_celery_beat_periodictask_priority_check" CHECK (("priority" >= 0)),
    CONSTRAINT "django_celery_beat_periodictask_total_run_count_check" CHECK (("total_run_count" >= 0))
);


ALTER TABLE "public"."django_celery_beat_periodictask" OWNER TO "postgres";


ALTER TABLE "public"."django_celery_beat_periodictask" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_celery_beat_periodictask_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_celery_beat_periodictasks" (
    "ident" smallint NOT NULL,
    "last_update" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_celery_beat_periodictasks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."django_celery_beat_solarschedule" (
    "id" integer NOT NULL,
    "event" character varying(24) NOT NULL,
    "latitude" numeric(9,6) NOT NULL,
    "longitude" numeric(9,6) NOT NULL
);


ALTER TABLE "public"."django_celery_beat_solarschedule" OWNER TO "postgres";


ALTER TABLE "public"."django_celery_beat_solarschedule" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_celery_beat_solarschedule_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_content_type" (
    "id" integer NOT NULL,
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL
);


ALTER TABLE "public"."django_content_type" OWNER TO "postgres";


ALTER TABLE "public"."django_content_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_content_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_migrations" (
    "id" bigint NOT NULL,
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_migrations" OWNER TO "postgres";


ALTER TABLE "public"."django_migrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_migrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_session" (
    "session_key" character varying(40) NOT NULL,
    "session_data" "text" NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_session" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."employees" (
    "id" integer NOT NULL,
    "account_id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "status" "public"."employee_status" DEFAULT 'active'::"public"."employee_status",
    "job_role" character varying(255),
    "phone_number" character varying(50),
    "email" character varying(255) NOT NULL,
    "slack_user_id" character varying(255),
    "slack_user_name" character varying(255),
    "reports_to" integer,
    "slack_workspace_id" "text",
    "timezone" "text"
);


ALTER TABLE "public"."employees" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."employees_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."employees_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."employees_id_seq" OWNED BY "public"."employees"."id";



CREATE TABLE IF NOT EXISTS "public"."ghl_locations" (
    "id" integer NOT NULL,
    "account_id" integer NOT NULL,
    "location_id" character varying(255) NOT NULL,
    "location_name" character varying(255)
);


ALTER TABLE "public"."ghl_locations" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ghl_locations_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."ghl_locations_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."ghl_locations_id_seq" OWNED BY "public"."ghl_locations"."id";



CREATE TABLE IF NOT EXISTS "public"."instalments" (
    "id" integer NOT NULL,
    "client_id" integer NOT NULL,
    "invoice_id" character varying(255),
    "stripe_customer_id" character varying(255),
    "stripe_account" character varying(255),
    "amount" numeric(10,2),
    "currency" character varying(10),
    "status" "public"."instalment_status" DEFAULT 'open'::"public"."instalment_status",
    "instalment_number" integer,
    "schedule_date" "date" NOT NULL,
    "date_created" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date_updated" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."instalments" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."instalments_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."instalments_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."instalments_id_seq" OWNED BY "public"."instalments"."id";



CREATE TABLE IF NOT EXISTS "public"."leads" (
    "account_id" integer NOT NULL,
    "first_name" character varying(255) NOT NULL,
    "last_name" character varying(255),
    "email" character varying(255) NOT NULL,
    "status" "text",
    "address" "text",
    "instagram_handle" character varying(255),
    "ghl_id" character varying(255),
    "created_at" "date",
    "dob" "date",
    "country" character varying(100),
    "state" character varying(100),
    "gender" character varying(50),
    "timezone" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" "uuid" NOT NULL
);


ALTER TABLE "public"."leads" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."packages" (
    "id" integer NOT NULL,
    "package_name" character varying(255) NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."packages" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."packages_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."packages_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."packages_id_seq" OWNED BY "public"."packages"."id";



CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" character varying(255) NOT NULL,
    "client_package_id" integer,
    "client_id" integer NOT NULL,
    "stripe_customer_id" character varying(255),
    "amount" numeric(10,2) NOT NULL,
    "currency" character varying(10),
    "exchange_rate" numeric(10,6),
    "native_account_currency" character varying(10),
    "status" "public"."payment_status" NOT NULL,
    "failure_reason" "text",
    "payment_date" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."payments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."short_urls" (
    "id" bigint NOT NULL,
    "short_code" "text",
    "original_url" "text" NOT NULL,
    "domain" "text",
    "title" "text" NOT NULL,
    "clicks" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "expires_at" timestamp with time zone,
    "is_active" boolean NOT NULL
);


ALTER TABLE "public"."short_urls" OWNER TO "postgres";


ALTER TABLE "public"."short_urls" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."short_urls_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."slack_accounts" (
    "workspace_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "workspace_name" "text" NOT NULL,
    "client_account_id" integer NOT NULL,
    "slack_access_token" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "onsync_bot_user_id" "text",
    "workspace_url" "text"
);


ALTER TABLE "public"."slack_accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stripe_api_keys" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "stripe_account" character varying,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "api_key" character varying,
    "client_account_id" integer,
    "id" integer NOT NULL,
    "is_active" boolean NOT NULL,
    "checkout_thanks_url" "text",
    "checkout_cancelled_url" "text"
);


ALTER TABLE "public"."stripe_api_keys" OWNER TO "postgres";


ALTER TABLE "public"."stripe_api_keys" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."stripe_api_keys_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."stripe_customers" (
    "id" integer NOT NULL,
    "account_id" integer NOT NULL,
    "client_id" integer NOT NULL,
    "stripe_customer_id" character varying(255) NOT NULL,
    "stripe_account" character varying(255),
    "email" character varying(255),
    "status" character varying(50)
);


ALTER TABLE "public"."stripe_customers" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."stripe_customers_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."stripe_customers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."stripe_customers_id_seq" OWNED BY "public"."stripe_customers"."id";



CREATE TABLE IF NOT EXISTS "public"."synchooks" (
    "id" bigint NOT NULL,
    "status" "text",
    "scheduled_datetime" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "client_id" integer,
    "account_id" integer,
    "success" boolean,
    "payload" json NOT NULL
);


ALTER TABLE "public"."synchooks" OWNER TO "postgres";


ALTER TABLE "public"."synchooks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."synchooks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tokens" (
    "id" integer NOT NULL,
    "access_token" "text" NOT NULL,
    "expires_in" integer,
    "refresh_token" "text" NOT NULL,
    "scope" "text",
    "token_type" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."tokens" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."tokens_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."tokens_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."tokens_id_seq" OWNED BY "public"."tokens"."id";



CREATE TABLE IF NOT EXISTS "public"."tracking_parameters" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "account_id" integer NOT NULL,
    "source" "text",
    "campaign" "text",
    "content" "text",
    "term" "text",
    "lead_id" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."tracking_parameters" OWNER TO "postgres";


ALTER TABLE "public"."tracking_parameters" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tracking_parameters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."webhooks_webhook" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "url" character varying(2048) NOT NULL,
    "http_method" character varying(10) NOT NULL,
    "headers" "jsonb" NOT NULL,
    "payload" "jsonb" NOT NULL,
    "schedule_type" character varying(20) NOT NULL,
    "cron_expression" character varying(100),
    "scheduled_at" timestamp with time zone,
    "timezone" character varying(50) NOT NULL,
    "is_active" boolean NOT NULL,
    "max_retries" integer NOT NULL,
    "retry_delay" integer NOT NULL,
    "timeout" integer NOT NULL,
    "celery_task_id" character varying(255),
    "celery_periodic_task_id" integer,
    "last_execution_at" timestamp with time zone,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "user_id" integer NOT NULL,
    "folder_id" bigint,
    "account_id" bigint
);


ALTER TABLE "public"."webhooks_webhook" OWNER TO "postgres";


ALTER TABLE "public"."webhooks_webhook" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."webhooks_webhook_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."webhooks_webhookexecution" (
    "id" bigint NOT NULL,
    "status" character varying(20) NOT NULL,
    "response_code" integer,
    "response_body" "text" NOT NULL,
    "error_message" "text" NOT NULL,
    "attempt_number" integer NOT NULL,
    "executed_at" timestamp with time zone NOT NULL,
    "webhook_id" bigint NOT NULL
);


ALTER TABLE "public"."webhooks_webhookexecution" OWNER TO "postgres";


ALTER TABLE "public"."webhooks_webhookexecution" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."webhooks_webhookexecution_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."webhooks_webhookfolder" (
    "id" bigint NOT NULL,
    "name" character varying(100) NOT NULL,
    "description" "text" NOT NULL,
    "color" character varying(7) NOT NULL,
    "icon" character varying(50) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "parent_id" bigint,
    "user_id" integer NOT NULL,
    "account_id" bigint
);


ALTER TABLE "public"."webhooks_webhookfolder" OWNER TO "postgres";


ALTER TABLE "public"."webhooks_webhookfolder" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."webhooks_webhookfolder_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."accounts" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."accounts_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."client_packages" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."client_packages_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."clients" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."clients_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."employees" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."employees_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."ghl_locations" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."ghl_locations_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."instalments" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."instalments_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."packages" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."packages_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."stripe_customers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."stripe_customers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."tokens" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tokens_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_ghl_location_id_key" UNIQUE ("ghl_location_id");



ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_trz_admin_user_id_key" UNIQUE ("trz_admin_user_id");



ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_trz_group_id_key" UNIQUE ("trz_group_id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");



ALTER TABLE ONLY "public"."auth_user"
    ADD CONSTRAINT "auth_user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");



ALTER TABLE ONLY "public"."auth_user"
    ADD CONSTRAINT "auth_user_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."authtoken_token"
    ADD CONSTRAINT "authtoken_token_pkey" PRIMARY KEY ("key");



ALTER TABLE ONLY "public"."authtoken_token"
    ADD CONSTRAINT "authtoken_token_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."click_analytics"
    ADD CONSTRAINT "click_analytics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."client_packages"
    ADD CONSTRAINT "client_packages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_celery_beat_clockedschedule"
    ADD CONSTRAINT "django_celery_beat_clockedschedule_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_celery_beat_crontabschedule"
    ADD CONSTRAINT "django_celery_beat_crontabschedule_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_celery_beat_intervalschedule"
    ADD CONSTRAINT "django_celery_beat_intervalschedule_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_celery_beat_periodictask"
    ADD CONSTRAINT "django_celery_beat_periodictask_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."django_celery_beat_periodictask"
    ADD CONSTRAINT "django_celery_beat_periodictask_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_celery_beat_periodictasks"
    ADD CONSTRAINT "django_celery_beat_periodictasks_pkey" PRIMARY KEY ("ident");



ALTER TABLE ONLY "public"."django_celery_beat_solarschedule"
    ADD CONSTRAINT "django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq" UNIQUE ("event", "latitude", "longitude");



ALTER TABLE ONLY "public"."django_celery_beat_solarschedule"
    ADD CONSTRAINT "django_celery_beat_solarschedule_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_migrations"
    ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_session"
    ADD CONSTRAINT "django_session_pkey" PRIMARY KEY ("session_key");



ALTER TABLE ONLY "public"."employees"
    ADD CONSTRAINT "employees_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."employees"
    ADD CONSTRAINT "employees_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ghl_locations"
    ADD CONSTRAINT "ghl_locations_account_id_location_id_key" UNIQUE ("account_id", "location_id");



ALTER TABLE ONLY "public"."ghl_locations"
    ADD CONSTRAINT "ghl_locations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."instalments"
    ADD CONSTRAINT "instalments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."packages"
    ADD CONSTRAINT "packages_package_name_key" UNIQUE ("package_name");



ALTER TABLE ONLY "public"."packages"
    ADD CONSTRAINT "packages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."short_urls"
    ADD CONSTRAINT "short_urls_domain_short_code_850f24aa_uniq" UNIQUE ("domain", "short_code");



ALTER TABLE ONLY "public"."short_urls"
    ADD CONSTRAINT "short_urls_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."slack_accounts"
    ADD CONSTRAINT "slack_accounts_pkey" PRIMARY KEY ("workspace_id");



ALTER TABLE ONLY "public"."stripe_api_keys"
    ADD CONSTRAINT "stripe_api_keys_api_key_key" UNIQUE ("api_key");



ALTER TABLE ONLY "public"."stripe_api_keys"
    ADD CONSTRAINT "stripe_api_keys_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stripe_api_keys"
    ADD CONSTRAINT "stripe_api_keys_stripe_account_key" UNIQUE ("stripe_account");



ALTER TABLE ONLY "public"."stripe_customers"
    ADD CONSTRAINT "stripe_customers_client_id_stripe_account_key" UNIQUE ("client_id", "stripe_account");



ALTER TABLE ONLY "public"."stripe_customers"
    ADD CONSTRAINT "stripe_customers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."stripe_customers"
    ADD CONSTRAINT "stripe_customers_stripe_customer_id_key" UNIQUE ("stripe_customer_id");



ALTER TABLE ONLY "public"."synchooks"
    ADD CONSTRAINT "synchooks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tokens"
    ADD CONSTRAINT "tokens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tracking_parameters"
    ADD CONSTRAINT "tracking_parameters_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."webhooks_webhook"
    ADD CONSTRAINT "webhooks_webhook_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."webhooks_webhookexecution"
    ADD CONSTRAINT "webhooks_webhookexecution_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."webhooks_webhookfolder"
    ADD CONSTRAINT "webhooks_webhookfolder_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."webhooks_webhookfolder"
    ADD CONSTRAINT "webhooks_webhookfolder_user_id_name_parent_id_0300968b_uniq" UNIQUE ("user_id", "name", "parent_id");



CREATE INDEX "auth_group_name_a6ea08ec_like" ON "public"."auth_group" USING "btree" ("name" "varchar_pattern_ops");



CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "public"."auth_group_permissions" USING "btree" ("group_id");



CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "public"."auth_group_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" USING "btree" ("content_type_id");



CREATE INDEX "auth_user_groups_group_id_97559544" ON "public"."auth_user_groups" USING "btree" ("group_id");



CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "public"."auth_user_groups" USING "btree" ("user_id");



CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "public"."auth_user_user_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "public"."auth_user_user_permissions" USING "btree" ("user_id");



CREATE INDEX "auth_user_username_6821ab7c_like" ON "public"."auth_user" USING "btree" ("username" "varchar_pattern_ops");



CREATE INDEX "authtoken_token_key_10f0b77e_like" ON "public"."authtoken_token" USING "btree" ("key" "varchar_pattern_ops");



CREATE INDEX "click_analy_clicked_dfb727_idx" ON "public"."click_analytics" USING "btree" ("clicked_at");



CREATE INDEX "click_analy_short_u_03e63f_idx" ON "public"."click_analytics" USING "btree" ("short_url_id", "clicked_at");



CREATE INDEX "click_analytics_clicked_at_497c0a65" ON "public"."click_analytics" USING "btree" ("clicked_at");



CREATE INDEX "click_analytics_short_url_id_0069751f" ON "public"."click_analytics" USING "btree" ("short_url_id");



CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "public"."django_admin_log" USING "btree" ("content_type_id");



CREATE INDEX "django_admin_log_user_id_c564eba6" ON "public"."django_admin_log" USING "btree" ("user_id");



CREATE INDEX "django_celery_beat_periodictask_clocked_id_47a69f82" ON "public"."django_celery_beat_periodictask" USING "btree" ("clocked_id");



CREATE INDEX "django_celery_beat_periodictask_crontab_id_d3cba168" ON "public"."django_celery_beat_periodictask" USING "btree" ("crontab_id");



CREATE INDEX "django_celery_beat_periodictask_interval_id_a8ca27da" ON "public"."django_celery_beat_periodictask" USING "btree" ("interval_id");



CREATE INDEX "django_celery_beat_periodictask_name_265a36b7_like" ON "public"."django_celery_beat_periodictask" USING "btree" ("name" "varchar_pattern_ops");



CREATE INDEX "django_celery_beat_periodictask_solar_id_a87ce72c" ON "public"."django_celery_beat_periodictask" USING "btree" ("solar_id");



CREATE INDEX "django_session_expire_date_a5c62663" ON "public"."django_session" USING "btree" ("expire_date");



CREATE INDEX "django_session_session_key_c0390e0f_like" ON "public"."django_session" USING "btree" ("session_key" "varchar_pattern_ops");



CREATE INDEX "short_urls_domain_0d3fde18" ON "public"."short_urls" USING "btree" ("domain");



CREATE INDEX "short_urls_domain_0d3fde18_like" ON "public"."short_urls" USING "btree" ("domain" "varchar_pattern_ops");



CREATE INDEX "short_urls_domain_628d7f_idx" ON "public"."short_urls" USING "btree" ("domain", "short_code");



CREATE INDEX "short_urls_short_c_01a9fd_idx" ON "public"."short_urls" USING "btree" ("short_code");



CREATE INDEX "short_urls_short_code_11717639" ON "public"."short_urls" USING "btree" ("short_code");



CREATE INDEX "short_urls_short_code_11717639_like" ON "public"."short_urls" USING "btree" ("short_code" "varchar_pattern_ops");



CREATE INDEX "webhooks_we_schedul_840684_idx" ON "public"."webhooks_webhook" USING "btree" ("schedule_type");



CREATE INDEX "webhooks_we_status_940060_idx" ON "public"."webhooks_webhookexecution" USING "btree" ("status");



CREATE INDEX "webhooks_we_user_id_51012d_idx" ON "public"."webhooks_webhook" USING "btree" ("user_id", "is_active");



CREATE INDEX "webhooks_we_user_id_6a82a8_idx" ON "public"."webhooks_webhookfolder" USING "btree" ("user_id", "parent_id");



CREATE INDEX "webhooks_we_webhook_2168e1_idx" ON "public"."webhooks_webhookexecution" USING "btree" ("webhook_id", "executed_at" DESC);



CREATE INDEX "webhooks_webhook_account_id_a7c58302" ON "public"."webhooks_webhook" USING "btree" ("account_id");



CREATE INDEX "webhooks_webhook_folder_id_a3a6a2ae" ON "public"."webhooks_webhook" USING "btree" ("folder_id");



CREATE INDEX "webhooks_webhook_user_id_6cbac57e" ON "public"."webhooks_webhook" USING "btree" ("user_id");



CREATE INDEX "webhooks_webhookexecution_webhook_id_4b70f683" ON "public"."webhooks_webhookexecution" USING "btree" ("webhook_id");



CREATE INDEX "webhooks_webhookfolder_account_id_5afbc985" ON "public"."webhooks_webhookfolder" USING "btree" ("account_id");



CREATE INDEX "webhooks_webhookfolder_parent_id_8463c5ec" ON "public"."webhooks_webhookfolder" USING "btree" ("parent_id");



CREATE INDEX "webhooks_webhookfolder_user_id_a8a3667b" ON "public"."webhooks_webhookfolder" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."authtoken_token"
    ADD CONSTRAINT "authtoken_token_user_id_35299eff_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."click_analytics"
    ADD CONSTRAINT "click_analytics_short_url_id_0069751f_fk_short_urls_id" FOREIGN KEY ("short_url_id") REFERENCES "public"."short_urls"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."client_packages"
    ADD CONSTRAINT "client_packages_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."client_packages"
    ADD CONSTRAINT "client_packages_package_id_fkey" FOREIGN KEY ("package_id") REFERENCES "public"."packages"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_closer_id_fkey" FOREIGN KEY ("closer_id") REFERENCES "public"."employees"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_coach_id_fkey" FOREIGN KEY ("coach_id") REFERENCES "public"."employees"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_setter_id_fkey" FOREIGN KEY ("setter_id") REFERENCES "public"."employees"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_celery_beat_periodictask"
    ADD CONSTRAINT "django_celery_beat_p_clocked_id_47a69f82_fk_django_ce" FOREIGN KEY ("clocked_id") REFERENCES "public"."django_celery_beat_clockedschedule"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_celery_beat_periodictask"
    ADD CONSTRAINT "django_celery_beat_p_crontab_id_d3cba168_fk_django_ce" FOREIGN KEY ("crontab_id") REFERENCES "public"."django_celery_beat_crontabschedule"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_celery_beat_periodictask"
    ADD CONSTRAINT "django_celery_beat_p_interval_id_a8ca27da_fk_django_ce" FOREIGN KEY ("interval_id") REFERENCES "public"."django_celery_beat_intervalschedule"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_celery_beat_periodictask"
    ADD CONSTRAINT "django_celery_beat_p_solar_id_a87ce72c_fk_django_ce" FOREIGN KEY ("solar_id") REFERENCES "public"."django_celery_beat_solarschedule"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."employees"
    ADD CONSTRAINT "employees_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."employees"
    ADD CONSTRAINT "employees_reports_to_fkey" FOREIGN KEY ("reports_to") REFERENCES "public"."employees"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."employees"
    ADD CONSTRAINT "employees_slack_workspace_id_fkey" FOREIGN KEY ("slack_workspace_id") REFERENCES "public"."slack_accounts"("workspace_id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."ghl_locations"
    ADD CONSTRAINT "ghl_locations_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."instalments"
    ADD CONSTRAINT "instalments_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_client_package_id_fkey" FOREIGN KEY ("client_package_id") REFERENCES "public"."client_packages"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."slack_accounts"
    ADD CONSTRAINT "slack_accounts_client_account_id_fkey" FOREIGN KEY ("client_account_id") REFERENCES "public"."accounts"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."stripe_api_keys"
    ADD CONSTRAINT "stripe_api_keys_client_account_id_fkey" FOREIGN KEY ("client_account_id") REFERENCES "public"."accounts"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."stripe_customers"
    ADD CONSTRAINT "stripe_customers_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."stripe_customers"
    ADD CONSTRAINT "stripe_customers_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."synchooks"
    ADD CONSTRAINT "synchooks_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."synchooks"
    ADD CONSTRAINT "synchooks_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."tracking_parameters"
    ADD CONSTRAINT "tracking_parameters_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tracking_parameters"
    ADD CONSTRAINT "tracking_parameters_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."webhooks_webhook"
    ADD CONSTRAINT "webhooks_webhook_account_id_a7c58302_fk_accounts_id" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."webhooks_webhook"
    ADD CONSTRAINT "webhooks_webhook_folder_id_a3a6a2ae_fk_webhooks_" FOREIGN KEY ("folder_id") REFERENCES "public"."webhooks_webhookfolder"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."webhooks_webhook"
    ADD CONSTRAINT "webhooks_webhook_user_id_6cbac57e_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."webhooks_webhookexecution"
    ADD CONSTRAINT "webhooks_webhookexec_webhook_id_4b70f683_fk_webhooks_" FOREIGN KEY ("webhook_id") REFERENCES "public"."webhooks_webhook"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."webhooks_webhookfolder"
    ADD CONSTRAINT "webhooks_webhookfold_parent_id_8463c5ec_fk_webhooks_" FOREIGN KEY ("parent_id") REFERENCES "public"."webhooks_webhookfolder"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."webhooks_webhookfolder"
    ADD CONSTRAINT "webhooks_webhookfolder_account_id_5afbc985_fk_accounts_id" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."webhooks_webhookfolder"
    ADD CONSTRAINT "webhooks_webhookfolder_user_id_a8a3667b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE "public"."accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."auth_group" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."auth_group_permissions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."auth_permission" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."auth_user" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."auth_user_groups" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."auth_user_user_permissions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."authtoken_token" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."click_analytics" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."client_packages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."clients" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_admin_log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_celery_beat_clockedschedule" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_celery_beat_crontabschedule" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_celery_beat_intervalschedule" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_celery_beat_periodictask" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_celery_beat_periodictasks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_celery_beat_solarschedule" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_content_type" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_migrations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."django_session" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."employees" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ghl_locations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."instalments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."leads" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."packages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."short_urls" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."slack_accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stripe_api_keys" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."stripe_customers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."synchooks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tokens" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tracking_parameters" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."webhooks_webhook" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."webhooks_webhookexecution" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."webhooks_webhookfolder" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."leads";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."accounts" TO "anon";
GRANT ALL ON TABLE "public"."accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."accounts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_group" TO "anon";
GRANT ALL ON TABLE "public"."auth_group" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_group" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_group_permissions" TO "anon";
GRANT ALL ON TABLE "public"."auth_group_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_group_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_permission" TO "anon";
GRANT ALL ON TABLE "public"."auth_permission" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_permission" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user" TO "anon";
GRANT ALL ON TABLE "public"."auth_user" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user_groups" TO "anon";
GRANT ALL ON TABLE "public"."auth_user_groups" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user_groups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "anon";
GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."authtoken_token" TO "anon";
GRANT ALL ON TABLE "public"."authtoken_token" TO "authenticated";
GRANT ALL ON TABLE "public"."authtoken_token" TO "service_role";



GRANT ALL ON TABLE "public"."click_analytics" TO "anon";
GRANT ALL ON TABLE "public"."click_analytics" TO "authenticated";
GRANT ALL ON TABLE "public"."click_analytics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."click_analytics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."click_analytics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."click_analytics_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."client_packages" TO "anon";
GRANT ALL ON TABLE "public"."client_packages" TO "authenticated";
GRANT ALL ON TABLE "public"."client_packages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."client_packages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."client_packages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."client_packages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."clients" TO "anon";
GRANT ALL ON TABLE "public"."clients" TO "authenticated";
GRANT ALL ON TABLE "public"."clients" TO "service_role";



GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_admin_log" TO "anon";
GRANT ALL ON TABLE "public"."django_admin_log" TO "authenticated";
GRANT ALL ON TABLE "public"."django_admin_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_celery_beat_clockedschedule" TO "anon";
GRANT ALL ON TABLE "public"."django_celery_beat_clockedschedule" TO "authenticated";
GRANT ALL ON TABLE "public"."django_celery_beat_clockedschedule" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_celery_beat_clockedschedule_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_clockedschedule_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_clockedschedule_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_celery_beat_crontabschedule" TO "anon";
GRANT ALL ON TABLE "public"."django_celery_beat_crontabschedule" TO "authenticated";
GRANT ALL ON TABLE "public"."django_celery_beat_crontabschedule" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_celery_beat_crontabschedule_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_crontabschedule_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_crontabschedule_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_celery_beat_intervalschedule" TO "anon";
GRANT ALL ON TABLE "public"."django_celery_beat_intervalschedule" TO "authenticated";
GRANT ALL ON TABLE "public"."django_celery_beat_intervalschedule" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_celery_beat_intervalschedule_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_intervalschedule_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_intervalschedule_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_celery_beat_periodictask" TO "anon";
GRANT ALL ON TABLE "public"."django_celery_beat_periodictask" TO "authenticated";
GRANT ALL ON TABLE "public"."django_celery_beat_periodictask" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_celery_beat_periodictask_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_periodictask_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_periodictask_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_celery_beat_periodictasks" TO "anon";
GRANT ALL ON TABLE "public"."django_celery_beat_periodictasks" TO "authenticated";
GRANT ALL ON TABLE "public"."django_celery_beat_periodictasks" TO "service_role";



GRANT ALL ON TABLE "public"."django_celery_beat_solarschedule" TO "anon";
GRANT ALL ON TABLE "public"."django_celery_beat_solarschedule" TO "authenticated";
GRANT ALL ON TABLE "public"."django_celery_beat_solarschedule" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_celery_beat_solarschedule_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_solarschedule_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_celery_beat_solarschedule_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_content_type" TO "anon";
GRANT ALL ON TABLE "public"."django_content_type" TO "authenticated";
GRANT ALL ON TABLE "public"."django_content_type" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_migrations" TO "anon";
GRANT ALL ON TABLE "public"."django_migrations" TO "authenticated";
GRANT ALL ON TABLE "public"."django_migrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_session" TO "anon";
GRANT ALL ON TABLE "public"."django_session" TO "authenticated";
GRANT ALL ON TABLE "public"."django_session" TO "service_role";



GRANT ALL ON TABLE "public"."employees" TO "anon";
GRANT ALL ON TABLE "public"."employees" TO "authenticated";
GRANT ALL ON TABLE "public"."employees" TO "service_role";



GRANT ALL ON SEQUENCE "public"."employees_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."employees_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."employees_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ghl_locations" TO "anon";
GRANT ALL ON TABLE "public"."ghl_locations" TO "authenticated";
GRANT ALL ON TABLE "public"."ghl_locations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ghl_locations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ghl_locations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ghl_locations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."instalments" TO "anon";
GRANT ALL ON TABLE "public"."instalments" TO "authenticated";
GRANT ALL ON TABLE "public"."instalments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."instalments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."instalments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."instalments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."leads" TO "anon";
GRANT ALL ON TABLE "public"."leads" TO "authenticated";
GRANT ALL ON TABLE "public"."leads" TO "service_role";



GRANT ALL ON TABLE "public"."packages" TO "anon";
GRANT ALL ON TABLE "public"."packages" TO "authenticated";
GRANT ALL ON TABLE "public"."packages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."packages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."packages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."packages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."payments" TO "anon";
GRANT ALL ON TABLE "public"."payments" TO "authenticated";
GRANT ALL ON TABLE "public"."payments" TO "service_role";



GRANT ALL ON TABLE "public"."short_urls" TO "anon";
GRANT ALL ON TABLE "public"."short_urls" TO "authenticated";
GRANT ALL ON TABLE "public"."short_urls" TO "service_role";



GRANT ALL ON SEQUENCE "public"."short_urls_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."short_urls_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."short_urls_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."slack_accounts" TO "anon";
GRANT ALL ON TABLE "public"."slack_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."slack_accounts" TO "service_role";



GRANT ALL ON TABLE "public"."stripe_api_keys" TO "anon";
GRANT ALL ON TABLE "public"."stripe_api_keys" TO "authenticated";
GRANT ALL ON TABLE "public"."stripe_api_keys" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stripe_api_keys_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stripe_api_keys_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stripe_api_keys_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."stripe_customers" TO "anon";
GRANT ALL ON TABLE "public"."stripe_customers" TO "authenticated";
GRANT ALL ON TABLE "public"."stripe_customers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."stripe_customers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."stripe_customers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."stripe_customers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."synchooks" TO "anon";
GRANT ALL ON TABLE "public"."synchooks" TO "authenticated";
GRANT ALL ON TABLE "public"."synchooks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."synchooks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."synchooks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."synchooks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tokens" TO "anon";
GRANT ALL ON TABLE "public"."tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."tokens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tracking_parameters" TO "anon";
GRANT ALL ON TABLE "public"."tracking_parameters" TO "authenticated";
GRANT ALL ON TABLE "public"."tracking_parameters" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tracking_parameters_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tracking_parameters_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tracking_parameters_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."webhooks_webhook" TO "anon";
GRANT ALL ON TABLE "public"."webhooks_webhook" TO "authenticated";
GRANT ALL ON TABLE "public"."webhooks_webhook" TO "service_role";



GRANT ALL ON SEQUENCE "public"."webhooks_webhook_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."webhooks_webhook_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."webhooks_webhook_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."webhooks_webhookexecution" TO "anon";
GRANT ALL ON TABLE "public"."webhooks_webhookexecution" TO "authenticated";
GRANT ALL ON TABLE "public"."webhooks_webhookexecution" TO "service_role";



GRANT ALL ON SEQUENCE "public"."webhooks_webhookexecution_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."webhooks_webhookexecution_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."webhooks_webhookexecution_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."webhooks_webhookfolder" TO "anon";
GRANT ALL ON TABLE "public"."webhooks_webhookfolder" TO "authenticated";
GRANT ALL ON TABLE "public"."webhooks_webhookfolder" TO "service_role";



GRANT ALL ON SEQUENCE "public"."webhooks_webhookfolder_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."webhooks_webhookfolder_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."webhooks_webhookfolder_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































