-- Add onboarding_link columns to clients table
-- Similar to checkin_link but for onboarding forms

-- Step 1: Add onboarding_link UUID column with unique constraint
ALTER TABLE clients ADD COLUMN IF NOT EXISTS onboarding_link UUID DEFAULT gen_random_uuid() UNIQUE;

-- Step 2: Add short_onboarding_link for shortened URLs
ALTER TABLE clients ADD COLUMN IF NOT EXISTS short_onboarding_link TEXT;

-- Step 3: Create index for faster lookups by onboarding_link
CREATE INDEX IF NOT EXISTS idx_clients_onboarding_link ON clients(onboarding_link);

-- Step 4: Update existing clients to have unique onboarding_link values
-- (The DEFAULT gen_random_uuid() handles this for new inserts, but existing rows need values)
UPDATE clients SET onboarding_link = gen_random_uuid() WHERE onboarding_link IS NULL;

-- Add comments
COMMENT ON COLUMN clients.onboarding_link IS 'Permanent UUID link for onboarding form access';
COMMENT ON COLUMN clients.short_onboarding_link IS 'Shortened URL for onboarding form (generated by URL shortener)';

